//user login

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

//user logout

export const LOGOUT_USER = "LOGOUT_USER";


// GROUP LIST
export const GET_GROUP_NAME_LIST = "GET_GROUP_NAME_LIST";
export const GET_GROUP_NAME_LIST_SUCCESS = "GET_GROUP_NAME_LIST_SUCCESS";
export const GET_GROUP_NAME_LIST_ERROR = "GET_GROUP_NAME_LIST_ERROR";


// ADD GROUP_NAME
export const ADD_GROUP_NAME = "ADD_GROUP_NAME";
export const ADD_GROUP_NAME_SUCCESS = "ADD_GROUP_NAME_SUCCESS";
export const ADD_GROUP_NAME_ERROR = "ADD_GROUP_NAME_ERROR";


// DELETE GROUP_NAME
export const DELETE_GROUP_NAME = "DELETE_GROUP_NAME";
export const DELETE_GROUP_NAME_SUCCESS = "DELETE_GROUP_NAME_SUCCESS";
export const DELETE_GROUP_NAME_ERROR = "DELETE_GROUP_NAME_ERROR";

// UPDATE GROUP_NAME
export const UPDATE_GROUP_NAME = "UPDATE_GROUP_NAME";
export const UPDATE_GROUP_NAME_SUCCESS = "UPDATE_GROUP_NAME_SUCCESS";
export const UPDATE_GROUP_NAME_ERROR = "UPDATE_GROUP_NAME_ERROR";

// SHOW GROUP_NAME
export const SHOW_GROUP_NAME = "SHOW_GROUP_NAME";
export const SHOW_GROUP_NAME_SUCCESS = "SHOW_GROUP_NAME_SUCCESS";
export const SHOW_GROUP_NAME_ERROR = "SHOW_GROUP_NAME_ERROR";



// GROUP LIST
export const GET_GROUP_CRITERIA_LIST = "GET_GROUP_CRITERIA_LIST";
export const GET_GROUP_CRITERIA_LIST_SUCCESS = "GET_GROUP_CRITERIA_LIST_SUCCESS";
export const GET_GROUP_CRITERIA_LIST_ERROR = "GET_GROUP_CRITERIA_LIST_ERROR";


// ADD GROUP_CRITERIA
export const ADD_GROUP_CRITERIA = "ADD_GROUP_CRITERIA";
export const ADD_GROUP_CRITERIA_SUCCESS = "ADD_GROUP_CRITERIA_SUCCESS";
export const ADD_GROUP_CRITERIA_ERROR = "ADD_GROUP_CRITERIA_ERROR";


// DELETE GROUP_CRITERIA
export const DELETE_GROUP_CRITERIA = "DELETE_GROUP_CRITERIA";
export const DELETE_GROUP_CRITERIA_SUCCESS = "DELETE_GROUP_CRITERIA_SUCCESS";
export const DELETE_GROUP_CRITERIA_ERROR = "DELETE_GROUP_CRITERIA_ERROR";

// UPDATE GROUP_CRITERIA
export const UPDATE_GROUP_CRITERIA = "UPDATE_GROUP_CRITERIA";
export const UPDATE_GROUP_CRITERIA_SUCCESS = "UPDATE_GROUP_CRITERIA_SUCCESS";
export const UPDATE_GROUP_CRITERIA_ERROR = "UPDATE_GROUP_CRITERIA_ERROR";

// SHOW GROUP_CRITERIA
export const SHOW_GROUP_CRITERIA = "SHOW_GROUP_CRITERIA";
export const SHOW_GROUP_CRITERIA_SUCCESS = "SHOW_GROUP_CRITERIA_SUCCESS";
export const SHOW_GROUP_CRITERIA_ERROR = "SHOW_GROUP_CRITERIA_ERROR";


// CAMPAIGN
// CAMPAIGN LIST
export const GET_CAMPAIGN_LIST = "GET_CAMPAIGN_LIST";
export const GET_CAMPAIGN_LIST_SUCCESS = "GET_CAMPAIGN_LIST_SUCCESS";
export const GET_CAMPAIGN_LIST_ERROR = "GET_CAMPAIGN_LIST_ERROR";


// ADD CAMPAIGN
export const ADD_CAMPAIGN = "ADD_CAMPAIGN";
export const ADD_CAMPAIGN_SUCCESS = "ADD_CAMPAIGN_SUCCESS";
export const ADD_CAMPAIGN_ERROR = "ADD_CAMPAIGN_ERROR";


// DELETE CAMPAIGN
export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN";
export const DELETE_CAMPAIGN_SUCCESS = "DELETE_CAMPAIGN_SUCCESS";
export const DELETE_CAMPAIGN_ERROR = "DELETE_CAMPAIGN_ERROR";

// DELETE CAMPAIGN
export const UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN";
export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_ERROR = "UPDATE_CAMPAIGN_ERROR";

// SHOW CAMPAIGN
export const SHOW_CAMPAIGN = "SHOW_CAMPAIGN";
export const SHOW_CAMPAIGN_SUCCESS = "SHOW_CAMPAIGN_SUCCESS";
export const SHOW_CAMPAIGN_ERROR = "SHOW_CAMPAIGN_ERROR";


// MESSAGE_TEMPLATE LIST
export const GET_MESSAGE_TEMPLATE_LIST = "GET_MESSAGE_TEMPLATE_LIST";
export const GET_MESSAGE_TEMPLATE_LIST_SUCCESS = "GET_MESSAGE_TEMPLATE_LIST_SUCCESS";
export const GET_MESSAGE_TEMPLATE_LIST_ERROR = "GET_MESSAGE_TEMPLATE_LIST_ERROR";


// ADD MESSAGE_TEMPLATE
export const ADD_MESSAGE_TEMPLATE = "ADD_MESSAGE_TEMPLATE";
export const ADD_MESSAGE_TEMPLATE_SUCCESS = "ADD_MESSAGE_TEMPLATE_SUCCESS";
export const ADD_MESSAGE_TEMPLATE_ERROR = "ADD_MESSAGE_TEMPLATE_ERROR";


// DELETE MESSAGE_TEMPLATE
export const DELETE_MESSAGE_TEMPLATE = "DELETE_MESSAGE_TEMPLATE";
export const DELETE_MESSAGE_TEMPLATE_SUCCESS = "DELETE_MESSAGE_TEMPLATE_SUCCESS";
export const DELETE_MESSAGE_TEMPLATE_ERROR = "DELETE_MESSAGE_TEMPLATE_ERROR";

// UPDATE MESSAGE_TEMPLATE
export const UPDATE_MESSAGE_TEMPLATE = "UPDATE_MESSAGE_TEMPLATE";
export const UPDATE_MESSAGE_TEMPLATE_SUCCESS = "UPDATE_MESSAGE_TEMPLATE_SUCCESS";
export const UPDATE_MESSAGE_TEMPLATE_ERROR = "UPDATE_MESSAGE_TEMPLATE_ERROR";

// SHOW MESSAGE_TEMPLATE
export const SHOW_MESSAGE_TEMPLATE = "SHOW_MESSAGE_TEMPLATE";
export const SHOW_MESSAGE_TEMPLATE_SUCCESS = "SHOW_MESSAGE_TEMPLATE_SUCCESS";
export const SHOW_MESSAGE_TEMPLATE_ERROR = "SHOW_MESSAGE_TEMPLATE_ERROR";

// MESSAGE_TEMPLATE LIST
export const GET_PUSH_NOTIFICATION_TEMPLATE_LIST = "GET_PUSH_NOTIFICATION_TEMPLATE_LIST";
export const GET_PUSH_NOTIFICATION_TEMPLATE_LIST_SUCCESS = "GET_PUSH_NOTIFICATION_TEMPLATE_LIST_SUCCESS";
export const GET_PUSH_NOTIFICATION_TEMPLATE_LIST_ERROR = "GET_PUSH_NOTIFICATION_TEMPLATE_LIST_ERROR";


// ADD  PUSH_NOTIFICATION_TEMPLATE
export const ADD_PUSH_NOTIFICATION_TEMPLATE = "ADD_PUSH_NOTIFICATION_TEMPLATE";
export const ADD_PUSH_NOTIFICATION_TEMPLATE_SUCCESS = "ADD_PUSH_NOTIFICATION_TEMPLATE_SUCCESS";
export const ADD_PUSH_NOTIFICATION_TEMPLATE_ERROR = "ADD_PUSH_NOTIFICATION_TEMPLATE_ERROR";

// SHOW  PUSH_NOTIFICATION_TEMPLATE
export const SHOW_PUSH_NOTIFICATION_TEMPLATE = "SHOW_PUSH_NOTIFICATION_TEMPLATE";
export const SHOW_PUSH_NOTIFICATION_TEMPLATE_SUCCESS = "SHOW_PUSH_NOTIFICATION_TEMPLATE_SUCCESS";
export const SHOW_PUSH_NOTIFICATION_TEMPLATE_ERROR = "SHOW_PUSH_NOTIFICATION_TEMPLATE_ERROR";

// DELETE PUSH_NOTIFICATION_TEMPLATE
export const DELETE_PUSH_NOTIFICATION_TEMPLATE = "DELETE_PUSH_NOTIFICATION_TEMPLATE";
export const DELETE_PUSH_NOTIFICATION_TEMPLATE_SUCCESS = "DELETE_PUSH_NOTIFICATION_TEMPLATE_SUCCESS";
export const DELETE_PUSH_NOTIFICATION_TEMPLATE_ERROR = "DELETE_PUSH_NOTIFICATION_TEMPLATE_ERROR";

// UPDATE PUSH_NOTIFICATION_TEMPLATE
export const UPDATE_PUSH_NOTIFICATION_TEMPLATE = "UPDATE_PUSH_NOTIFICATION_TEMPLATE";
export const UPDATE_PUSH_NOTIFICATION_TEMPLATE_SUCCESS = "UPDATE_PUSH_NOTIFICATION_TEMPLATE_SUCCESS";
export const UPDATE_PUSH_NOTIFICATION_TEMPLATE_ERROR = "UPDATE_PUSH_NOTIFICATION_TEMPLATE_ERROR";


// EMAIL_TEMPLATE LIST
export const GET_EMAIL_TEMPLATE_LIST = "GET_EMAIL_TEMPLATE_LIST";
export const GET_EMAIL_TEMPLATE_LIST_SUCCESS = "GET_EMAIL_TEMPLATE_LIST_SUCCESS";
export const GET_EMAIL_TEMPLATE_LIST_ERROR = "GET_EMAIL_TEMPLATE_LIST_ERROR";


// ADD EMAIL_TEMPLATE
export const ADD_EMAIL_TEMPLATE = "ADD_EMAIL_TEMPLATE";
export const ADD_EMAIL_TEMPLATE_SUCCESS = "ADD_EMAIL_TEMPLATE_SUCCESS";
export const ADD_EMAIL_TEMPLATE_ERROR = "ADD_EMAIL_TEMPLATE_ERROR";


// DELETE EMAIL_TEMPLATE
export const DELETE_EMAIL_TEMPLATE = "DELETE_EMAIL_TEMPLATE";
export const DELETE_EMAIL_TEMPLATE_SUCCESS = "DELETE_EMAIL_TEMPLATE_SUCCESS";
export const DELETE_EMAIL_TEMPLATE_ERROR = "DELETE_EMAIL_TEMPLATE_ERROR";

// DELETE EMAIL_TEMPLATE
export const UPDATE_EMAIL_TEMPLATE = "UPDATE_EMAIL_TEMPLATE";
export const UPDATE_EMAIL_TEMPLATE_SUCCESS = "UPDATE_EMAIL_TEMPLATE_SUCCESS";
export const UPDATE_EMAIL_TEMPLATE_ERROR = "UPDATE_EMAIL_TEMPLATE_ERROR";

// SHOW EMAIL_TEMPLATE
export const SHOW_EMAIL_TEMPLATE = "SHOW_EMAIL_TEMPLATE";
export const SHOW_EMAIL_TEMPLATE_SUCCESS = "SHOW_EMAIL_TEMPLATE_SUCCESS";
export const SHOW_EMAIL_TEMPLATE_ERROR = "SHOW_EMAIL_TEMPLATE_ERROR";
